In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# circles_dataset = pd.read_csv('moons1.csv')
# circles_dataset = pd.read_csv('circles0.3.csv')
# circles_dataset = pd.read_csv('halfkernel.csv')
# circles_dataset = pd.read_csv('spiral1.csv')
# circles_dataset = pd.read_csv('twogaussians33.csv')
# circles_dataset = pd.read_csv('twogaussians42.csv')
circles_dataset = pd.read_csv('Breastcancer.csv')
X_circles = circles_dataset.iloc[:,:-1].values
Y_circles = circles_dataset.iloc[:,-1].values
Y_circles = Y_circles.reshape(-1,1)

In [ ]:
from sklearn.model_selection import train_test_split
X_circles_train,X_circles_test,Y_circles_train,Y_circles_test = train_test_split(X_circles,Y_circles, test_size=0.2, random_state=0)

### Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
circles_dt_classifier = DecisionTreeClassifier(random_state=0,criterion = 'entropy')
circles_dt_classifier.fit(X_circles_train,Y_circles_train)
Y_circles_dt_pred = circles_dt_classifier.predict(X_circles_test)

from sklearn.metrics import confusion_matrix, accuracy_score
circles_dt_cm = confusion_matrix(Y_circles_test,Y_circles_dt_pred)
print ("Confusion matrix for circles Dataset with DT classifier is : ")
print(circles_dt_cm)

circles_dt_ac = (accuracy_score(Y_circles_test,Y_circles_dt_pred)*100)
print ("Accuracy for circles Dataset with DT classifier is :")
print(circles_dt_ac)

Confusion matrix for circles Dataset with DT classifier is : 
[[6 1 0 0 0]
 [0 6 0 1 1]
 [0 1 8 0 0]
 [0 1 4 3 0]
 [0 0 0 0 0]]
Accuracy for circles Dataset with DT classifier is :
71.875


In [ ]:
import sklearn.metrics
import math
def matrix_metrix(Y_circles_test,Y_circles_dt_pred,beta):
   CM = confusion_matrix(Y_circles_test,Y_circles_dt_pred)
   TN = CM[0][0]
   FN = CM[1][0] 
   TP = CM[1][1]
   FP = CM[0][1]
   Population = TN+FN+TP+FP
   Prevalence = round( (TP+FP) / Population*100)
   Sensitivity= round(TP/(TP+FN)*100)
   Specificity= round(TN/(TN+FP)*100)
   Accuracy   = round( (TP+TN)/ Population*100,4)
   PPV  = round(( TP / (TP+FP))*100,2)
   NPV        = round( TN / (TN+FN)*100,2)  
   mat_met = pd.DataFrame({
'Metric':['TP','TN','FP','FN','Prevalence','Sensitivity','Specificity','Accuracy','PPV','NPV'],     'Value':[TP,TN,FP,FN,Prevalence,Sensitivity,Specificity,Accuracy,PPV,NPV]})
   return (mat_met)

In [ ]:
beta = 0.4
mat_met = matrix_metrix(Y_circles_test,Y_circles_dt_pred,beta)
#convert float into integer
def round_int(x):
    if x in [float("-inf"),float("inf")]: return float("nan")
    return int(round(x))
print (mat_met)

        Metric     Value
0           TP    6.0000
1           TN    6.0000
2           FP    1.0000
3           FN    0.0000
4   Prevalence   54.0000
5  Sensitivity  100.0000
6  Specificity   86.0000
7     Accuracy   92.3077
8          PPV   85.7100
9          NPV  100.0000


### Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
circles_RF_classifier = RandomForestClassifier( random_state=0, criterion = 'entropy', n_estimators = 150)
circles_RF_classifier.fit(X_circles_train,Y_circles_train)
Y_circles_RF_pred = circles_RF_classifier.predict(X_circles_test)

from sklearn.metrics import confusion_matrix, accuracy_score
circles_RF_cm = confusion_matrix(Y_circles_test,Y_circles_RF_pred)
print ("Confusion matrix for circles Dataset with RF classifier is : ")
print(circles_RF_cm)

circles_RF_ac = (accuracy_score(Y_circles_test,Y_circles_RF_pred)*100)
print ("Accuracy for circles Dataset with RF classifier is :")
print(circles_RF_ac)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


Confusion matrix for circles Dataset with RF classifier is : 
[[7 0 0 0]
 [0 7 0 1]
 [0 0 9 0]
 [0 0 6 2]]
Accuracy for circles Dataset with RF classifier is :
78.125


In [ ]:
import sklearn.metrics
import math
def matrix_metrix(Y_circles_test,Y_circles_RF_pred,beta):
   CM = confusion_matrix(Y_circles_test,Y_circles_RF_pred)
   TN = CM[0][0]
   FN = CM[1][0] 
   TP = CM[1][1]
   FP = CM[0][1]
   Population = TN+FN+TP+FP
   Prevalence = round( (TP+FP) / Population*100)
   Sensitivity= round(TP/(TP+FN)*100)
   Specificity= round(TN/(TN+FP)*100)
   Accuracy   = round( (TP+TN)/ Population*100,4)
   PPV  = round(( TP / (TP+FP))*100,2)
   NPV        = round( TN / (TN+FN)*100,2)  
   mat_met = pd.DataFrame({
'Metric':['TP','TN','FP','FN','Prevalence','Sensitivity','Specificity','Accuracy','PPV','NPV'],     'Value':[TP,TN,FP,FN,Prevalence,Sensitivity,Specificity,Accuracy,PPV,NPV]})
   return (mat_met)

In [ ]:
beta = 0.4
mat_met = matrix_metrix(Y_circles_test,Y_circles_RF_pred,beta)
#convert float into integer
def round_int(x):
    if x in [float("-inf"),float("inf")]: return float("nan")
    return int(round(x))
print (mat_met)

        Metric  Value
0           TP    7.0
1           TN    7.0
2           FP    0.0
3           FN    0.0
4   Prevalence   50.0
5  Sensitivity  100.0
6  Specificity  100.0
7     Accuracy  100.0
8          PPV  100.0
9          NPV  100.0


### Neural Networks using Multi-layer Perceptron Classifier from SKlearn 


In [ ]:
from sklearn.neural_network import MLPClassifier
circles_NN_classifier = MLPClassifier(solver = 'lbfgs', activation = 'logistic')
circles_NN_classifier.fit(X_circles_train,Y_circles_train)
Y_circles_NN_pred = circles_NN_classifier.predict(X_circles_test)

from sklearn.metrics import confusion_matrix, accuracy_score
circles_NN_cm = confusion_matrix(Y_circles_test,Y_circles_NN_pred)
print ("Confusion matrix for circles Dataset with MLP classifier is : ")
print(circles_NN_cm)

circles_NN_ac = (accuracy_score(Y_circles_test,Y_circles_NN_pred)*100)
print ("Accuracy for circles Dataset with MLP classifier is :")
print(circles_NN_ac)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Confusion matrix for circles Dataset with MLP classifier is : 
[[7 0 0 0]
 [0 8 0 0]
 [0 0 9 0]
 [0 1 5 2]]
Accuracy for circles Dataset with MLP classifier is :
81.25


In [ ]:
import sklearn.metrics
import math
def matrix_metrix(Y_circles_test,Y_circles_NN_pred,beta):
   CM = confusion_matrix(Y_circles_test,Y_circles_NN_pred)
   TN = CM[0][0]
   FN = CM[1][0] 
   TP = CM[1][1]
   FP = CM[0][1]
   Population = TN+FN+TP+FP
   Prevalence = round( (TP+FP) / Population*100)
   Sensitivity= round(TP/(TP+FN)*100)
   Specificity= round(TN/(TN+FP)*100)
   Accuracy   = round( (TP+TN)/ Population*100,4)
   PPV  = round(( TP / (TP+FP))*100,2)
   NPV        = round( TN / (TN+FN)*100,2)  
   mat_met = pd.DataFrame({
'Metric':['TP','TN','FP','FN','Prevalence','Sensitivity','Specificity','Accuracy','PPV','NPV'],     'Value':[TP,TN,FP,FN,Prevalence,Sensitivity,Specificity,Accuracy,PPV,NPV]})
   return (mat_met)

In [ ]:
beta = 0.4
mat_met = matrix_metrix(Y_circles_test,Y_circles_NN_pred,beta)
#convert float into integer
def round_int(x):
    if x in [float("-inf"),float("inf")]: return float("nan")
    return int(round(x))
print (mat_met)

        Metric  Value
0           TP    8.0
1           TN    7.0
2           FP    0.0
3           FN    0.0
4   Prevalence   53.0
5  Sensitivity  100.0
6  Specificity  100.0
7     Accuracy  100.0
8          PPV  100.0
9          NPV  100.0
